### ISSUE TITLE
The problematic use of mustache syntax for marking languages

### ISSUE THREAD

**Issue by JackAtOmenApps** [OmenApps/PolyglotMarkdown#1]
As noted in the discussion on Mastodon [here](https://mastodon.social/@EmmaDelescolle/113027510163140204), the use of mustache syntax for marking languages, which is used by a significant number of template processors (Django, Jinja, Handlebars, ...), will likely be problematic and incompatible with other tools.

## Questions raised:

- How does the syntax choice reconcile with this?
- Are unknown tags simply ignored?
- Or can something like {%raw%} be used?

## Things to consider in a new approach

When using a Markdown parser that is unaware of PolyglotMarkdown, should the preferred behavior be ~~to hide the portion, section, and transclusion (include) markers (in which case language content may be jumbled together), or~~ to show them, making it clear that the document was not parsed correctly?

### Potential approach 1: HTML Comments

- `<!-- lang:"es" -->` or `<!-- lang="es" -->`
- `<!-- include:"file.md" lang:"es" -->` or `<!-- include="file.md" lang="es" -->`

### Potential approach 2: Sad Robot Syntax

After reviewing a multitude of potential markings, I found the vast majority of easy 2-character markings are used by programming languages, mathematical convention, or Markdown itself. The one exception that that I found that is short, easy to type and read, and does not seem to conflict with any other language of formatting/templating system I could find is the colon-square-bracket, as shown below:

:[en]: This is a paragraph in English.
:[es]: Este es un párrafo en español.

:[lang:en]:
This is a section in English.

:[lang:es]:
Esta es una sección en español.

:[include "external_file.md" lang="en"]:

This seems to work well, but I would appreciate community feedback!

## This also brings up another question

Should we prefer colons (`:`) or equal signs (`=`)?

- :[lang:es]:
- :[lang=es]:

**Comment by nanuxbe** [comment]
> The one exception that that I found that is short, easy to type and read

I wouldn't get too hung up on the "easy to type" part as this will vastly depend on the keyboard layout. For example, the Belgian and French layouts (or probably any layout that is made for an accented language) are awful for `[]` and `{}` but, AFAIK, it's not a major deterrent for people using them.

Given the nature of this project, a significant portion of the target audience will not be using a US or UK layout and accounting for every single keyboard layout there is, is probably not constructive, especially at this point.

**Comment by jacklinke** [comment]
@nanuxbe That makes a lot of sense. Not sure how I totally glossed over that.

That said, the Colon + Square-Bracket approach seems easy to read and doesn't appear to conflict with any other tools.

Do you foresee any potential problems using it?

Edit: same person here, logged into personal account.

**Comment by JackAtOmenApps** [comment]
Updated the README to use the `:[es]:` format, which I am now calling "Sad Robot Syntax" 🤖 in c7ea77b107103b0c103de8094ee8bc16a134893c

**Comment by nanuxbe** [comment]
Sad robot sounds better than 70s-stache :P
