### ISSUE TITLE
Other advantage of using a single file approach

### ISSUE THREAD

**Issue by nanuxbe** [OmenApps/PolyglotMarkdown#2]
In the [Why Would I Use This Instead of Separate Files for Each Language?](https://github.com/OmenApps/PolyglotMarkdown?tab=readme-ov-file#why-would-i-use-this-instead-of-separate-files-for-each-language) section, one of the biggest advantages that spring to my mind is partially translated content which often appears on multi-lingual websites as content of lesser value and/or interest is often left untranslated "for later" (and it might or might not get translated in the end).

If you are using a multi-file approach, this means you'll have to copy-paste such sections from file to file, whereas, with the fallback mechanism mentioned here, you can have some sections only available in the fallback language.

Even if you discount document that should to be translated at a future date, there are things that do not require translations, code snippets and math formulas spring to mind here.

**Comment by jacklinke** [comment]
Fantastic points.

The more I hear from folks on this project, the more things I realize I hadn't considered or had never run into myself.

I'll work on adding this to the Readme tomorrow.

**Comment by JackAtOmenApps** [comment]
Incorporated your notes into the README in d8bcf1c158c4900ca9a6a0bcc7b65b560f4678b1
